Repository jupyterlite/pyodide-kernel, pull requests merged in 2023-08, with the labels that each got.

#51 Add `before-bump-version` hook
  pyproject.toml
Labels: maintenance

#50 Update to Pyodide 0.23.4
  jupyterlite_pyodide_kernel/constants.py
  packages/pyodide-kernel-extension/schema/kernel.v0.schema.json
  packages/pyodide-kernel-extension/src/index.ts
  packages/pyodide-kernel/package.json
  yarn.lock
Labels: enhancement

#53 Add `version_info` to the `ipykernel` mock
  packages/pyodide-kernel/py/ipykernel/ipykernel/__init__.py
Labels: bug

#54 Make use of the new Comm package
  packages/pyodide-kernel/py/ipykernel/ipykernel/comm.py
  packages/pyodide-kernel/py/pyodide-kernel/pyodide_kernel/comm.py
  packages/pyodide-kernel/py/pyodide-kernel/pyodide_kernel/display.py
  packages/pyodide-kernel/py/pyodide-kernel/pyodide_kernel/jsonutil.py
  packages/pyodide-kernel/py/pyodide-kernel/pyodide_kernel/kernel.py
  packages/pyodide-kernel/src/worker.ts
Labels: maintenance

#55 Bumped @jupyterlite packages
  packages/pyodide-kernel-extension/package.json
  packages/pyodide-kernel/package.json
  yarn.lock
Labels: maintenance
