Repository jupyterlite/pyodide-kernel, pull requests merged in 2024-03, with the labels that each got.

#102 Fix lint
  packages/pyodide-kernel/py/piplite/piplite/piplite.py
  pyproject.toml
Labels: maintenance

#101 Update releaser workflows
  .github/workflows/prep-release.yml
  .github/workflows/publish-release.yml
Labels: maintenance

#100 Bump `@jupyterlite` packages
  packages/pyodide-kernel-extension/package.json
  packages/pyodide-kernel/package.json
  pyproject.toml
  yarn.lock
Labels: maintenance

#103 Support `loadPyodide` options
  examples/jupyter-lite.json
  package.json
  packages/pyodide-kernel-extension/schema/kernel.v0.schema.json
  packages/pyodide-kernel-extension/src/index.ts
  packages/pyodide-kernel/src/kernel.ts
  packages/pyodide-kernel/src/tokens.ts
  packages/pyodide-kernel/src/worker.ts
Labels: enhancement

#104 Update compat table in README.md
  README.md
Labels: documentation

#105 Fix URL rewriting in `loadPyodideOptions`
  examples/jupyter-lite.json
  packages/pyodide-kernel-extension/src/index.ts
  packages/pyodide-kernel/src/kernel.ts
  packages/pyodide-kernel/src/tokens.ts
Labels: enhancement
