Repository jupyterlite/pyodide-kernel, pull requests merged in 2024-12, with the labels that each got.

#148 Use postMessage instead of a comlink produced MessageChannel
  packages/pyodide-kernel/package.json
  packages/pyodide-kernel/src/comlink.worker.ts
  packages/pyodide-kernel/src/kernel.ts
  yarn.lock
Labels: bug

#149 Update to JupyterLite 0.5.0
  .github/workflows/test.yml
  README.md
  packages/pyodide-kernel-extension/package.json
  packages/pyodide-kernel/package.json
  pyproject.toml
  ui-tests/package.json
  ui-tests/yarn.lock
  yarn.lock
Labels: enhancement

#150 Update `jupyterlite-core` dependency
  pyproject.toml
Labels: maintenance

#151 Drop Python 3.8
  .github/workflows/test.yml
  pyproject.toml
Labels: maintenance
