Repository jupyterlite/pyodide-kernel, pull requests merged in 2024-02, with the labels that each got.

#82 Update to pyodide 0.25.0
  LICENSE
  docs/conf.py
  examples/intro.ipynb
  jupyterlite_pyodide_kernel/_version.py
  jupyterlite_pyodide_kernel/addons/_base.py
  jupyterlite_pyodide_kernel/app.py
  jupyterlite_pyodide_kernel/constants.py
  jupyterlite_pyodide_kernel/tests/conftest.py
  jupyterlite_pyodide_kernel/tests/test_piplite.py
  jupyterlite_pyodide_kernel/tests/test_pyodide.py
  jupyterlite_pyodide_kernel/tests/test_repo.py
  package.json
  packages/pyodide-kernel-extension/LICENSE
  packages/pyodide-kernel-extension/schema/kernel.v0.schema.json
  packages/pyodide-kernel-extension/src/index.ts
  packages/pyodide-kernel/LICENSE
  packages/pyodide-kernel/package.json
  packages/pyodide-kernel/py/ipykernel/LICENSE
  packages/pyodide-kernel/py/piplite/LICENSE
  packages/pyodide-kernel/py/piplite/piplite/__init__.py
  packages/pyodide-kernel/py/piplite/piplite/cli.py
  packages/pyodide-kernel/py/piplite/piplite/piplite.py
  packages/pyodide-kernel/py/pyodide-kernel/LICENSE
  packages/pyodide-kernel/py/pyodide-kernel/pyodide_kernel/litetransform.py
  packages/pyodide-kernel/py/pyodide-kernel/pyodide_kernel/mocks.py
  packages/pyodide-kernel/py/pyodide-kernel/pyproject.toml
  packages/pyodide-kernel/py/widgetsnbextension3/widgetsnbextension/LICENSE
  packages/pyodide-kernel/py/widgetsnbextension4/widgetsnbextension/LICENSE
  pyproject.toml
  setup.py
  yarn.lock
Labels: maintenance

#84 pin to jupyterlab <4.1.0 for now in build-system and dev
  .github/workflows/check-release.yml
  .github/workflows/prep-release.yml
  .github/workflows/publish-release.yml
  .github/workflows/test.yml
  pyproject.toml
Labels: maintenance

#86 Bump widgetsnbextension shim to 4.0.10
  examples/intro.ipynb
  examples/jupyter_lite_config.json
  packages/pyodide-kernel/package.json
  packages/pyodide-kernel/py/widgetsnbextension4/widgetsnbextension/widgetsnbextension/__init__.py
  packages/pyodide-kernel/src/_pypi.ts
  pyproject.toml
Labels: maintenance

#92 docs: add information on compatibility with pyodide versions
  README.md
Labels: documentation

#93 Update to JupyterLite `0.3.0a0`
  README.md
  packages/pyodide-kernel-extension/package.json
  packages/pyodide-kernel/package.json
  pyproject.toml
  yarn.lock
Labels: enhancement
