Repository jupyterlite/pyodide-kernel, pull requests merged in 2025-05, with the labels that each got.

#183 Support stdin via service worker
  packages/pyodide-kernel/src/coincident.worker.ts
  packages/pyodide-kernel/src/comlink.worker.ts
  packages/pyodide-kernel/src/kernel.ts
  packages/pyodide-kernel/src/tokens.ts
  packages/pyodide-kernel/src/worker.ts
Labels: enhancement

#187 Log messages to the dev tools console
  packages/pyodide-kernel/src/worker.ts
Labels: bug

#188 Log Pyodide fatal errors
  packages/pyodide-kernel/src/worker.ts
Labels: enhancement

#189 Update to Pyodide 0.27.6
  examples/jupyter-lite.json
  jupyterlite_pyodide_kernel/constants.py
  packages/pyodide-kernel-extension/schema/kernel.v0.schema.json
  packages/pyodide-kernel-extension/src/index.ts
  packages/pyodide-kernel/package.json
  yarn.lock
Labels: maintenance

#190 Update to JupyterLite 0.6.0rc0
  packages/pyodide-kernel-extension/package.json
  packages/pyodide-kernel/package.json
  pyproject.toml
  yarn.lock
Labels: maintenance
